### ISSUE TITLE
Feedback zu eTOC (moritz strickler, post ch ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#11]
ch.fhir.ig.ch-etoc#0.1.0 /

1. Sind Anhänge nur für den Care-Plan möglich? Wie können bspw. weitere Dokumente mitgesendet werden?
2. Es kann immer nur ein Empfänger für eine Zuweisung angegeben werden. Bspw. Bei Heimeinweisungen oder Reha ist es gängig, dass die Zuweisung an mehrere Empfänger geht. Kann dies mit dem eToc IG abgedeckt werden?

moritz strickler, post ch ag

**Comment by JBleuer** [comment]
Splitted in two issues

**Comment by pjolo** [comment]
@JBleuer Into which two issue was this splited up?

**Comment by JBleuer** [comment]
#22 for issue for 1.
#23 for issue 2; now closed
