### ISSUE TITLE
CH eToc Service Request - Definitions medication statement instead of medication card (Walter Wellauer, Cistec  AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#20]
ch.fhir.ig.ch-etoc#0.1.0 /StructureDefinition-ch-etoc-servicerequest-definitions.html

instead of http://fhir.ch/ig/ch-etoc/StructureDefinition-ch-etoc-servicerequest-definitions.html#ServiceRequest.supportingInfo:medicationcard
reference to medicationstatment should be used.
Reason:
practitioner will choose medcation statements by user interaction and not a medication card

Walter Wellauer, Cistec  AG

**Comment by JBleuer** [comment]
Changed to Medication Statement (Version for use with MedicationCard)

**Comment by JBleuer** [comment]
branch newmedication: medication changed to medicationstatement and dosage unstrucured.
@ziegm : Please review

**Comment by JBleuer** [comment]
@walterwellauer: medication changed to medicationstatement and dosage unstrucured merged into main
