### ISSUE TITLE
Reference to the IPAG report

### ISSUE THREAD

**Issue by drats-cis** [hl7ch/ch-etoc#21]
I miss the inclusion of numerous aspects from the preliminary work of the IPAG, cf. report:
[https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2016/D/160119_eAustrittsbericht_Bericht_IPAG_D.pdf](url)
For example, more comprehensive use cases are addressed there or the different views of the professional groups.

Daniel Ratschiller, Cistec AG

**Comment by JBleuer** [comment]
See also https://github.com/hl7ch/ch-etoc/issues/4#issue-953837328:
A reference to eToC / eÜberweisungsbericht
should be added and the relation between the IG and the IPAG document be described.

**Comment by pjolo** [comment]
For me it looks good and I close the issue
