### ISSUE TITLE
Home - Check spelling and referring links (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#3]
ch.fhir.ig.ch-etoc#0.1.0 /

A Spell checking on the content seems necessary: On the home page i noted:  th IPS, preferance, condsidered, alergy, ServiceReequest

It would be nice if references to specs could be linked: eg FHIR International Patient Summary (IPS), Swiss eHealth Exchange Format Handbook Part I: Service Requests V 0.13. 

Oliver Egger, ahdis

**Comment by JBleuer** [comment]
typos mentionned above corrected
Issue is closed; opened new one with:
- Proof Reading
- Add links in text: It would be nice if references to specs could be linked: eg FHIR International Patient Summary (IPS), Swiss eHealth Exchange Format Handbook Part I: Service Requests V 0.13.
