### ISSUE TITLE
Home - Missing reference to IPAG report (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#4]
ch.fhir.ig.ch-etoc#0.1.0 /

A reference to eToC / eÜberweisungsbericht
should be added and the relation between the IG and the IPAG document be described.

Oliver Egger, ahdis

**Comment by JBleuer** [comment]
Merged with #21

**Comment by drats-cis** [comment]
The correct link to **eÜberweisungsbericht (eTransition-of-Care Dokument)** 3. Bericht of Interprofessionelle Arbeitsgruppe Elektronisches Patientendossier would be:
https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2018/D/181206_eTOC-eUeberweisungsbericht-IPAG_d.pdf

**Comment by JBleuer** [comment]
Link added
