### ISSUE TITLE
Questionnaire Electronic Transition of Care (axsana AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#40]
ch.fhir.ig.ch-etoc#1.0.0 /Questionnaire-QuestionnaireEtoc.html

Ist die Kardinalität von "Patient" mit 0..1 korrekt. Unser Vorschlag wäre 1..1.
Bzw. was wäre der UseCase, dass man Etoc ohne Patient verwendet?

axsana AG

**Comment by JBleuer** [comment]
is set to 1..1

**Comment by pjolo** [comment]
Checked and issue closed.
