### ISSUE TITLE
Profiles: duplicate (Michaela Ziegler, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#46]
ch.fhir.ig.ch-etoc#1.1.0 /profiles.html

The profile 'CH eTOC Care Plan' is listed twice

Michaela Ziegler, ahdis

**Comment by JBleuer** [comment]
Solved

**Comment by JBleuer** [comment]
Solved

**Comment by pjolo** [comment]
Checked and issue closed.
