### ISSUE TITLE
Composition.section (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#48]
ch.fhir.ig.ch-etoc#1.1.0 /StructureDefinition-ch-etoc-composition.html

There are some copy & paste errors (e.g. careplans, medication), incl. content of sections
![image](https://user-images.githubusercontent.com/32767151/187680375-d4032877-3669-4594-8338-bf07f199ff8b.png)

A few section.title have the same value: "Anamesis", shouldn't they be different from each other?

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Corrected together with #38
