### ISSUE TITLE
CH eToc Service Request: German naming and MedicationStatement instead of MedicationCard (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#5]
ch.fhir.ig.ch-etoc#0.1.0 /StructureDefinition-ch-etoc-servicerequest.html

Ziel und Begründung: -> translate to english
supportingInfo:medicationcard is 0..1 MedicationStatement, this cannot be a Medication Card (Description is: Medication Card contains n medications with dosages)

Oliver Egger, ahdis

**Comment by JBleuer** [comment]
Translation done; Issue medication card solved; see #20
