### ISSUE TITLE
Usage of Attachment (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-etoc#50]
The following points are not clear to me for the usage of the profile [CH eTOC Attachment](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/StructureDefinition-ch-etoc-attachment.html):
* Why is this structure derived from [ChEtocMedia](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/StructureDefinition-ch-etoc-media.html)?
   * There is no additional restrictions, why is an additional profile necessary?
   * It is confusing to call the profile from type Media 'Attachment' because there is also an [Attachment data type](https://www.hl7.org/fhir/datatypes.html#Attachment).
   * A more detailed description of the profile would be helpful for understanding ('Definition for the Attachment').
   * An example of an attachment would also be helpful.
* Composition.section:sectionAttachment
   * Copy & paste errors from careplan: section description, title, code
   * Wouldn't it be better to have an attachment embedded in the DocumentReference resource?
      * Does it then need a separate section? Could it not be mapped here: Composition.section:orderReferral.entry:DocumentReference

**Comment by pjolo** [comment]
OK for me
