### ISSUE TITLE
Compositon.section:sectionPurpose (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#51]
ch.fhir.ig.ch-etoc#1.1.0 /StructureDefinition-ch-etoc-composition.html

Because of copy & paste, the information of this section is analogue to the description of the medication section. So it is not quite clear, what the purpose of this section is, especially because the referenced resource is the ServiceRequest, which is already contained in the section:orderReferral.

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Copy paste errors corrected. Referenced resource is the ServiceRequest (not changed; as discussed with Michaela)

**Comment by pjolo** [comment]
OK for me
