### ISSUE TITLE
Typos (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#53]
* ch.fhir.ig.ch-etoc#1.1.0 /StructureDefinition-ch-etoc-composition.html: Allergies and **intoerlancies**
* ch.fhir.ig.ch-etoc#1.1.0 /StructureDefinition-ch-etoc-primary-diagnosis.html: CH **Relectronic tranisiton** of care
* Changelog: and **shonw** no more in the questionnaire
* Changelog: subject of **furhter disussions**
* Composition profile: Allergies and **intoerlancies**
* Artifacts: **t**HistoryofIllnessesCondition

**Comment by JBleuer** [comment]
Fixed
