### ISSUE TITLE
Questionnaire: allergyIntolerance.status mapping (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#57]
ch.fhir.ig.ch-etoc#1.1.0 /Questionnaire-QuestionnaireEtoc.html

What is expected in this field for an indication and in which element of AllergyIntolerances is it mapped? (Is there an example in the IG?)

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Example added:

Instance: AllergyIntolerance
InstanceOf: ChEtocAllergyIntolerance
Title: "Allergy / Intolerance"
Description: "Example for Allergy / Intolerancce"
* code.text = "Anamnestisch Penicillinallergie"
* patient = Reference(SUfferer)

**Comment by JBleuer** [comment]
Added this to #59
