### ISSUE TITLE
 immunization -> Allergien und Intoleranzen (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#58]
ch.fhir.ig.ch-etoc#1.1.0 /Questionnaire-QuestionnaireEtoc.html

Im Questionnaire hat das Item den falschen Titel 

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Titel changed to "Impfstatus".

**Comment by pjolo** [comment]
Good for me
