### ISSUE TITLE
unclear mapping (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-etoc#59]
ch.fhir.ig.ch-etoc#1.1.0 /Questionnaire-QuestionnaireEtoc.html

What is expected in these fields and in which element of the Observation is it mapped? (Is there an example in the IG?)

- lab.result 0..*
- pathology.result 0..1
- imaging.result 0..1
- cardiology.result 0..1

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Examples for Lab Results:

itle: "Haemoglobin"
Description: "Example for Lab Result"
* status = #final
* code.text = "Hb: 112 g/l"
* subject = Reference(SUfferer)


Instance: HbA1c
InstanceOf: ChEtocLabObservation
Title: "Hb-A1c"
Description: "Example for Lab Result"
* status = #final
* code.text = "HHb-A1c: 5.4 %"
* subject = Reference(SUfferer)

**Comment by JBleuer** [comment]
Instance: AllergyIntolerance
InstanceOf: ChEtocAllergyIntolerance
Title: "Allergy / Intolerance"
Description: "Example for Allergy / Intolerance"
* code.text = "Anamnestisch Penicillinallergie"
* patient = Reference(SUfferer)


Instance: Haemoglobin
InstanceOf: ChEtocLabObservation
Title: "Haemoglobin"
Description: "Example for Lab Result"
* status = #final
* code.text = "Hb: 112 g/l"
* subject = Reference(SUfferer)


Instance: HbA1c
InstanceOf: ChEtocLabObservation
Title: "Hb-A1c"
Description: "Example for Lab Result"
* status = #final
* code.text = "HHb-A1c: 5.4 %"
* subject = Reference(SUfferer)


Instance: Biopsie
InstanceOf: ChEtocPathologyObservation
Title: "Biopsie Duodenum / Magen"
Description: "Example for Pathology Result"
* status = #final
* code.text = "Biopsien Duodenum, Magen, unruhige Z-Linie vom 19.09.2018:
Die Veränderungen der Duodenalschleimhaut passen gut zu einem geringen petpischen Schleimhautschaden. Die Magenschleimhaut zeigt das Bild einer reaktiven Gastropathie. Erosive Veränderungen gelangen hier nicht zur Darstellung. Kein Helicopacter, keine Metaplasie, keine pathogenen Erreger nachgeewiesen."
* subject = Reference(SUfferer)


Instance: Imaging
InstanceOf: ChEtocRadiologyObservation
Title: "Thx ap / seitl."
Description: "Example for Imaging Result"
* status = #final
* code.text = "Thorax ap / seitl. vom 12.05.23: unauffällig"
* subject = Reference(SUfferer)


Instance: 
InstanceOf: ChEtocCardiologyObservation
Title: "EKG"
Description: "Example for Cardiology Result"
* status = #final
* code.text = "EKG vom 12.5.23: unauffällig"
* subject = Reference(SUfferer)

**Comment by JBleuer** [comment]
Includes also  #57: Questionnaire: allergyIntolerance.status mapping (Michaela Ziegler, ahdis ag)

**Comment by JBleuer** [comment]
Issues to disucuss (all these entries):
1  Text formatting (bold, new line etc): fhir allows for MD; what is our oppinion?
Except lab, all entries have cardinality 0..1: Reason: According to IPAG, in a first step, the items shall be implemented as text.
It can be expected, that users want to copy paste results: it  seems sensible, to have multiple entries for lab, but other findings are mostly in freetext and therefore it makes sense to copy all findings in one copy-paste action.

**Comment by JBleuer** [comment]
Text above pasted in home.

**Comment by JBleuer** [comment]
No textformatting for now.

**Comment by pjolo** [comment]
This ticket is closed because it is done
