### ISSUE TITLE
 appointment.location.name (axsana AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#63]
ch.fhir.ig.ch-etoc#1.0.0 /

Ein Zuweiser hat die Möglichkeit, einen Zeitraum zu definieren, wann der Folgetermin stattfinden soll (appointment.requestedPeriod). Wenn der Zuweiser dies ausfüllt, muss er aber auch die appointment.location.name mitteilen.
Uns ist nicht klar, was der Mehrwert ist, wenn bereits unter receiver.organization die notwendige Informationen mitgeteilt wurden.
Wir verstehen auch nicht, wie  appointment.location.name mit appointment.requestedPeriod zusammenhängt. Ein Zuweiser soll doch in der Lage sein, appointment.requestedPeriod auszufüllen, ohne  appointment.location.name zu verwenden?

axsana AG

**Comment by JBleuer** [comment]
Appointment location is now 0..1. This allows to indicate location and period independently. The item location serves the following purpose: In case an organization provides services at different locations (e.g. a hmo with multiple offices), the location allows to define at whih office the service is scheduled.

**Comment by JBleuer** [comment]
publisher problem is in orf

**Comment by pjolo** [comment]
Good for me
