### ISSUE TITLE
Fehler im ServiceRequest Purpose / purpose.aim (Dick Driessen / axsana AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#64]
ch.fhir.ig.ch-etoc#1.0.0 /

purpose.aim kann nicht die Kardinalität 1..* haben, denn dieser wird von CH ORF ServiceRequest vererbt. Hier ist eine Kardinalität von 0..1 definiert.

Somit sollte im eTOC die Kardinalität bei purpose.aim auf 1..1 angepasst werden. 

Dick Driessen / axsana AG

**Comment by JBleuer** [comment]
Corrected and aded purpose.aim.detail in order to allow multiple entries.

**Comment by JBleuer** [comment]
Ad: For "Questionnaire eTOC (Modular version)" there is an error message in the IG: Unable to resolve 'order' sub-questionnaire..
-> Questionnaires are now assembled
Ad QuestionniaireResponse...
-> Name changed to QuestionniaireResponse. Medical Referral; code corrected

**Comment by pjolo** [comment]
This ticket is closed because it is done
