### ISSUE TITLE
Questionnaire Electronic Transition of Care (David Gutknecht - openmedical AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#65]
ch.fhir.ig.ch-etoc#1.0.0 /Questionnaire-QuestionnaireEtoc.html

diagnosisList.primarydiagnosis -> diagnosisList.primaryDiagnosis
to be consistent with
diagnosisList.primaryDiagnosis.item

Also same remark for diagnosisList.secondaryDiagnosis

There is also a tipping error on 
attachtment.title -> attachment.title

David Gutknecht - openmedical AG

**Comment by JBleuer** [comment]
typo and camelCase corrected
