### ISSUE TITLE
Questionnaire linkid's:

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-etoc#69]
Questionnaire linkid's: changed medication.statement.medication and medication.medicationstatement.dosage to medication.medication and medication.dosage in order to be inline with other. likid's

**Comment by JBleuer** [comment]
Adapted representation in questionnaire

**Comment by pjolo** [comment]
In Ex_Questionnaire.fsh is
item[+].linkId = "Kardiologie" is reversed with
item[=].text = "cardiology"

item[+].linkId = "Kardiologie" should be item[+].linkId = "cardiology
item[=].text = "cardiology" should be item[=].text = "Kardiologie"

![image](https://github.com/hl7ch/ch-etoc/assets/87263053/12d0c61d-4f16-4f5d-bee0-b9d6a7d0e4f9)

**Comment by pjolo** [comment]
This ticket is closed because it is done
