### ISSUE TITLE
Home (Gabriel Hess, BFH I4MI)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#76]
ch.fhir.ig.ch-etoc#2.0.0-ballot /

Die Links zu den Composition Sections funktionieren nicht.
Ausserdem zahlreiche Typos:
### Kapitel 1.1
- [ ] „hispital“ statt „hospital“
- [ ] my be implemented“ statt „may be implemented 
### Kapitel 1.2 
- [ ] Überflüssiges „>“ nach dem FHIR R4 Link
- [ ] „the the HL7 Switzerland Technical Committee“ (doppeltes the)
- [ ] „disccussed“ statt „discussed“
- [ ]  „questionnaie“ statt „Questionnaire“
- [ ] generell Questionnaire und QuestionnaireResponse nicht einheitlich, z.T. gross geschrieben, z.T. klein, Questionnaire Response zum Teil auseinander
- [ ] „Swiss Core“ statt „CH Core“
- [ ] „secctions“ statt „sections“
- [ ] „condsidered“ statt „considered“
- [ ] „Copy receiver is ment“ statt „… is meant“

Gabriel Hess, BFH I4MI

**Comment by pjolo** [comment]
Various typos on the home page corrected
See [Home](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/index.html)
Update [changelog](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/changelog.html)
