### ISSUE TITLE
Home: IG Fragments (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#78]
ch.fhir.ig.ch-etoc#2.0.0-ballot /

Add the recommended fragments, see CH Core:
http://fhir.ch/ig/ch-core/index.html

Safety Considerations
IP Statements
Cross Version Analysis
Dependency Table
Globals Table

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
https://raw.githubusercontent.com/hl7ch/ch-core/master/input/pagecontent/index.md

**Comment by pjolo** [comment]
IG Fregements have been added at the bottom of the home page see:
[Safety Considerations](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/index.html#safety-considerations)
[IP Statements](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/index.html#ip-statements)
[Cross Version Analysis](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/index.html#cross-version-analysis)
[Dependency Table](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/index.html#dependency-table)
[Globals Table](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/index.html#globals-table)

And [changelog](url)
