### ISSUE TITLE
Use Cases: link the corresponding Bundles (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#8]
ch.fhir.ig.ch-etoc#0.1.0 /usecase-english.html

For the users, the direct link to the corresponding bundle for the use case (JSON, XML) would be helpful

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Direct link to the corresponding bundle for the use case (JSON, XML) added in English decription of use cases only
