### ISSUE TITLE
Error in Questionnaire: Item Attachment

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-etoc#81]
* item[=].item.linkId = "attachment.title"
* item[=].item.definition = "http://fhir.ch/ig/ch-orf/StructureDefinition/ch-orf-documentreferencet#content.attachment.title"
* item[=].item.text = "Dateiname und -endung der angehängten Datei (z.B. \"Verlauf.pdf\")"
* item[=].item.type = #string
* item[=].item.repeats = true

"ch-orf-documentreferencet#content.attachment.title should" be "ch-orf-documentreference#content.attachment.title"

**Comment by JBleuer** [comment]
fixed and changelog with issue #81 updated

**Comment by pjolo** [comment]
Good
