### ISSUE TITLE
Use CH Core base profiles

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-etoc#83]
- Parent profiles:
   - ChEtocAllergyIntolerance
   - ChEtocPrimaryDiagnosisCondition
   - ChEtocSecondaryDiagnosisCondition
   - ChEtocPastHistoryofIllnessesCondition

- References to CH EMED changed to CH Core for:
   - CHCoreMedicationStatement
   - CHCoreMedication
   - CHCoreDosage

remove then dependencies to following igs 
  ch.fhir.ig.ch-emed: current
  ch.fhir.ig.ch-vacd: current
  ch.fhir.ig.ch-allergyintolerance: current

**Comment by ziegm** [comment]
@pjolo please review the changes mentioned in the first entry
https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue83_chcorebaseprofiles/index.html

**Comment by pjolo** [comment]
The adaptations are good
