### ISSUE TITLE
Typo in Questionnaire

### ISSUE THREAD

**Issue by JBleuer** [hl7ch/ch-etoc#85]
attachment.title:
Definition: http://fhir.ch/ig/ch-orf/StructureDefinition/ch-orf-documentreferencet#content.attachment.title

Corrected to 

Definition: http://fhir.ch/ig/ch-orf/StructureDefinition/ch-orf-documentreference#content.attachment.title

...ocumentreferencet#content... --> dropped "t"

**Comment by ziegm** [comment]
https://build.fhir.org/ig/hl7ch/ch-etoc/branches/main/Questionnaire-ch-etoc-module-attachment.json.html

**Comment by pjolo** [comment]
Change is good
