### ISSUE TITLE
Bundle Medical Referral: wrong Questionnaire (url) (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#9]
ch.fhir.ig.ch-etoc#0.1.0 /Bundle-DocumentEtoc.xml.html

QA: The questionnaire 'http://fhir.ch/ig/ch-rad-order/Questionnaire/QuestionnaireEtoc' could not be resolved, so no validation can be performed against the base questionnaire

Wrong url in:
- Bundle-DocumentEtoc
- QuestionnaireResponse-QuestionnaireResponseEtoc

Michaela Ziegler, ahdis ag

**Comment by JBleuer** [comment]
Solved in the course of #14
