### ISSUE TITLE
Home - Dependencies (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#90]
ch.fhir.ig.ch-etoc#3.0.0-ballot /

Should the IG not be referencing to the ch-ips and derive from theire profiles?

Roeland Luykx (RALY GmbH)

**Comment by ziegm** [comment]
@ralych @pjolo @JBleuer 
Could you please review my proposal:
- In the published version, it was described (as text on home), that CH eTOC does not depend on UV IPS, but in the dependency table, the UV IPS was listet. So I removed the unused dependency to UV IPS. And according to the statement, to not claim to be conform to IPS, we would not add the dependeny to CH IPS.
- For a better understanding I tried to update the part with the relationship to the IPS:
   - Add a title for the section
   - Removed/updated version-independent links (to be consistent with the current published versions)
   - Added CH IPS (new introduced) in the statements/descriptions
   - Updated the table: 
      - added CH eTOC section column, to have a direct comparison
      - added comment column, to have the comments directly at the right place (till now underneath the table) 
      - removed parent profile row (to avoid inconsistency, especially from parent profiles from other IGs)
      - updated the table concerning the sections of the new IPS version 
      
 - [Dependency Table](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue90_ips/index.html#dependency-table)
 - [Section Relationship to IPS](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue90_ips/index.html#relation-to-the-international-patient-summary)
 - [Changelog](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue90_ips/changelog.html)

**Comment by pjolo** [comment]
> @ralych @pjolo @JBleuer Could you please review my proposal:
> 
> * In the published version, it was described (as text on home), that CH eTOC does not depend on UV IPS, but in the dependency table, the UV IPS was listet. So I removed the unused dependency to UV IPS. And according to the statement, to not claim to be conform to IPS, we would not add the dependeny to CH IPS.
> * For a better understanding I tried to update the part with the relationship to the IPS:
>   
>   * Add a title for the section
>   * Removed/updated version-independent links (to be consistent with the current published versions)
>   * Added CH IPS (new introduced) in the statements/descriptions
>   * Updated the table:
>     
>     * added CH eTOC section column, to have a direct comparison
>     * added comment column, to have the comments directly at the right place (till now underneath the table)
>     * removed parent profile row (to avoid inconsistency, especially from parent profiles from other IGs)
>     * updated the table concerning the sections of the new IPS version
> 
> ci build:
> 
> * [Dependency Table](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue90_ips/index.html#dependency-table)
> * [Section Relationship to IPS](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue90_ips/index.html#relation-to-the-international-patient-summary)
> * [Changelog](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/issue90_ips/changelog.html)

@ziegm: Perfect, for me, the changes and descriptions are good. Thank you very much.

**Comment by ralych** [comment]
@pjolo @ziegm @JBleuer It is ok for me too. I formulated this issue only because i saw the dependency. I did not make a check if it was used. I this case anyway better to have as less dependencies as possible.

**Comment by JBleuer** [comment]
@ziegm : https://github.com/hl7ch/ch-etoc/pull/98/commits/4ccb2f7e84427e16c27d95c87efccbb49964e018: Should section[sectionPregnancyHx].entry 0.. MS not be 0..1 MS ?

**Comment by ziegm** [comment]
> @ziegm : [4ccb2f7](https://github.com/hl7ch/ch-etoc/commit/4ccb2f7e84427e16c27d95c87efccbb49964e018): Should section[sectionPregnancyHx].entry 0.. MS not be 0..1 MS ?

@JBleuer 
you habe two different observation:
![image](https://github.com/user-attachments/assets/01ddb350-f029-434f-b72f-77081ad95060)
you could support them both, couldn't you?

**Comment by JBleuer** [comment]
Delivery Date is more precise and includes positive pregnancy status. The idea is that someone idicates delivery date if known and/or clinically meaningful. If for one or another reason the date is not known, it is at least possible to set the pegnacy status to positive. This makes sense because this information is important for many things (medication, X-rays etc.) and it is therefore crucial that this can be indicated in cases where delivery date is not known/available.  To allow both would require a plausibility check or auomtatism in order to prevent garbage. Pregnancy status OR delivery date makes things simpler.

**Comment by JBleuer** [comment]
@ziegm see above
