### ISSUE TITLE
Anwendungsfälle (Roeland Luykx, RALY GmbH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-etoc#92]
ch.fhir.ig.ch-etoc#3.0.0-ballot /

on top of the page is "TBD" written. Still open stuff?
and
Missing links to corresponding profiles and examples

Roeland Luykx, RALY GmbH

**Comment by pjolo** [comment]
@JBleuer 

- At 2.1 [Transition of care letter](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/usecases/usecase-english.html#transition-of-care-letter) please change “Related” with “Associated

- At 2.2 [Request for a letter of discharge from earlier](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/usecases/usecase-english.html#request-for-a-discharge-letter-from-earlier) below there is "Translated with DeepL.com (free version)" please remove

- Please remove TBD under 3 [Anwendungsfälle](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/usecases/usecase-german.html#anwendungsf%C3%A4lle)

**Comment by JBleuer** [comment]
"Related" changed to "associated", Deepl removed, TBD removed

**Comment by pjolo** [comment]
Adjustments are good
