### ISSUE TITLE
Broken links in Home/Foundation

### ISSUE THREAD

**Issue by mrunibe** [hl7ch/ch-etoc#93]
Under https://fhir.ch/ig/ch-etoc/index.html#foundation the following links are broken:

![image](https://github.com/user-attachments/assets/88e617c6-0d53-4035-a032-46a538243ceb)

**Comment by pjolo** [comment]
@mrunibe 
all broken links have been fixed [Home](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/Issue93-broken-links-in-homefoundation/index.html)
[Changelog](https://build.fhir.org/ig/hl7ch/ch-etoc/branches/Issue93-broken-links-in-homefoundation/changelog.html)

**Comment by mrunibe** [comment]
Looks good!
